### PR TITLE
cargo: openssh-keys release 0.4.0 

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by lucab** [comment]
I've pushed the corresponding tag: https://github.com/coreos/openssh-keys/releases/tag/v0.4.0.

@sdemos can you please `cargo owner --add` the @coreos/team-os-internal-crates-owners to this crate so that I can publish the corresponding crate?

**Comment by sdemos** [comment]
@lucab should be good now. let me know if it's not, I wasn't 100% on the syntax.

**Comment by lucab** [comment]
@sdemos yes, that was fine.

Published: https://crates.io/crates/openssh-keys/0.4.0

**Pull request merged**
